CREATE DATABASE IF NOT EXISTS chatting;
USE chatting;

CREATE TABLE IF NOT EXISTS room (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  createAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS chat (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  room VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  `when` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS serverInfo (
  ip VARCHAR(255) PRIMARY KEY,
  available BOOLEAN DEFAULT TRUE
); 